services:
  reservation-db:
    image: postgres:16
    environment:
      POSTGRES_DB: reservation
      POSTGRES_USER: reservation
      POSTGRES_PASSWORD: reservation
    ports:
      - "5432:5432"
  operation-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: operation
      MYSQL_USER: operation
      MYSQL_PASSWORD: operation
      MYSQL_ROOT_PASSWORD: operation
    ports:
      - "3306:3306"
