spring:
  application:
    name: operation
  datasource:
    url: jdbc:mysql://localhost:3306/operation
    username: operation
    password: operation
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8082
