spring:
  application:
    name: operation
  datasource:
    url: jdbc:mysql://localhost:3306/operation
    username: operation
    password: operation
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8082

outbox-event:
  batch-size: 20
  max-retry-count: 5
  initial-backoff-seconds: 30
  max-backoff-seconds: 1800
  poll-interval-millis: 5000
