package yeo.chi.proejct.pms.reservation.configuration

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration
import org.springframework.scheduling.annotation.EnableScheduling

@Configuration
@EnableScheduling
@EnableConfigurationProperties(OutboundNotificationDispatchProperties::class)
class SchedulingConfiguration
